# Generated by Django 6.1.1 on 2026-09-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_facultyprofile_status"),
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="current_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="ocr_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="teacher_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="analysis_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="decision",
            field=models.CharField(default="ACCEPTED", max_length=50),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="highest_match_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="highest_match_student",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="matched_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_by",
                to="assignments.assignmentsubmission",
            ),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="processing_status",
            field=models.CharField(default="LOW_SIMILARITY", max_length=50),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="teacher_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="teacher_review_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="assignments/submissions/"
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("OCR_COMPLETED", "OCR Completed"),
                    ("CHECKING_SIMILARITY", "Checking Similarity"),
                    ("LOW_SIMILARITY", "Low Similarity"),
                    ("HIGH_SIMILARITY", "High Similarity"),
                    ("REVIEW_REQUESTED", "Review Requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("REWRITE_REQUIRED", "Rewrite Required"),
                    ("RESUBMITTED", "Resubmitted"),
                    ("Late", "Late"),
                    ("Graded", "Graded"),
                ],
                default="SUBMITTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="similarityresult",
            name="originality_percentage",
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name="similarityresult",
            name="similarity_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="similarityresult",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarity_result",
                to="assignments.assignmentsubmission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together={("assignment", "student")},
        ),
        migrations.CreateModel(
            name="SimilarityMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_student_name", models.CharField(max_length=200)),
                ("matched_student_name", models.CharField(max_length=200)),
                ("similarity_percentage", models.FloatField()),
                ("matching_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_target",
                        to="assignments.assignmentsubmission",
                    ),
                ),
                (
                    "source_submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_source",
                        to="assignments.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_percentage"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/submissions/versions/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="SUBMITTED", max_length=30)),
                ("ocr_text", models.TextField(blank=True, default="")),
                ("ocr_status", models.CharField(default="COMPLETED", max_length=30)),
                ("ocr_confidence", models.FloatField(default=0.0)),
                ("similarity_percentage", models.FloatField(default=0.0)),
                ("originality_percentage", models.FloatField(default=100.0)),
                ("decision", models.CharField(blank=True, default="", max_length=50)),
                ("teacher_feedback", models.TextField(blank=True, default="")),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="assignments.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["version_number"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="assignments/submissions/pages/")),
                ("page_number", models.IntegerField(default=1)),
                ("ocr_page_text", models.TextField(blank=True, default="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_files",
                        to="assignments.assignmentsubmission",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="assignments.submissionversion",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="OCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ocr_text", models.TextField()),
                ("ocr_status", models.CharField(default="COMPLETED", max_length=30)),
                ("ocr_confidence", models.FloatField(default=0.0)),
                ("page_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="assignments.assignmentsubmission",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="assignments.submissionversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="similarityresult",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="similarity_results",
                to="assignments.submissionversion",
            ),
        ),
        migrations.CreateModel(
            name="TeacherReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                (
                    "matched_student",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REWRITE_REQUESTED", "Rewrite Requested"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.facultyprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="assignments.assignmentsubmission",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="assignments.submissionversion",
                    ),
                ),
            ],
        ),
    ]
